"""add_auth_and_tenancy

Revision ID: 4ebc45702d35
Revises: 0002_rag_schema
Create Date: 2026-05-28 14:18:22.266877
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4ebc45702d35'
down_revision = '0002_rag_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_roles_tenant_id'), 'roles', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('quota_docs', sa.BigInteger(), nullable=False),
    sa.Column('quota_tokens', sa.BigInteger(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('memberships',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id')
    )
    op.create_index(op.f('ix_memberships_tenant_id'), 'memberships', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.alter_column('chunks', 'embedding_status',
               existing_type=postgresql.ENUM('pending', 'embedded', 'failed', name='embedding_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_chunks_content_tsv'), table_name='chunks', postgresql_using='gin', postgresql_where='(content_tsv IS NOT NULL)')
    op.drop_index(op.f('ix_chunks_embedding_hnsw'), table_name='chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.drop_index(op.f('ix_citations_document_id'), table_name='citations')
    op.alter_column('conversations', 'total_messages',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'total_tokens_used',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'ready', 'failed', 'quarantined', name='document_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'language',
               existing_type=sa.VARCHAR(length=8),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'status',
               existing_type=postgresql.ENUM('queued', 'running', 'succeeded', 'failed', 'retrying', 'dead', name='job_status'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'stage',
               existing_type=postgresql.ENUM('queued', 'extract', 'ocr', 'chunk', 'embed', 'index', 'done', 'error', name='ingestion_stage'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'has_citations',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'citation_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_failures', 'is_terminal',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('refresh_tokens', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip', postgresql.INET(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'revoked')
    op.alter_column('retrieval_logs', 'vector_results_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'bm25_results_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'reranked_results_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'final_context_chunks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'context_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'was_compressed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'cache_hit',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'debug_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_retrieval_logs_message_id'), table_name='retrieval_logs')
    op.alter_column('semantic_cache', 'hit_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_semantic_cache_embedding_hnsw'), table_name='semantic_cache', postgresql_ops={'query_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(query_embedding IS NOT NULL)')
    op.drop_index(op.f('ix_semantic_cache_expires_at'), table_name='semantic_cache')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_constraint(op.f('uq_users_tenant_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_tenant_email'), 'users', ['tenant_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'password_hash')
    op.create_index(op.f('ix_semantic_cache_expires_at'), 'semantic_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_semantic_cache_embedding_hnsw'), 'semantic_cache', ['query_embedding'], unique=False, postgresql_ops={'query_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(query_embedding IS NOT NULL)')
    op.alter_column('semantic_cache', 'hit_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_retrieval_logs_message_id'), 'retrieval_logs', ['message_id'], unique=False)
    op.alter_column('retrieval_logs', 'debug_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'cache_hit',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'was_compressed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'context_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'final_context_chunks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'reranked_results_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'bm25_results_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('retrieval_logs', 'vector_results_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.drop_column('refresh_tokens', 'updated_at')
    op.drop_column('refresh_tokens', 'ip')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'revoked_at')
    op.alter_column('processing_failures', 'is_terminal',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('messages', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('messages', 'citation_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('messages', 'has_citations',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'stage',
               existing_type=postgresql.ENUM('queued', 'extract', 'ocr', 'chunk', 'embed', 'index', 'done', 'error', name='ingestion_stage'),
               server_default=sa.text("'queued'::ingestion_stage"),
               existing_nullable=False)
    op.alter_column('ingestion_jobs', 'status',
               existing_type=postgresql.ENUM('queued', 'running', 'succeeded', 'failed', 'retrying', 'dead', name='job_status'),
               server_default=sa.text("'queued'::job_status"),
               existing_nullable=False)
    op.alter_column('documents', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('documents', 'language',
               existing_type=sa.VARCHAR(length=8),
               server_default=sa.text("'tr'::character varying"),
               existing_nullable=False)
    op.alter_column('documents', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'ready', 'failed', 'quarantined', name='document_status'),
               server_default=sa.text("'pending'::document_status"),
               existing_nullable=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.alter_column('conversations', 'is_archived',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('conversations', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('conversations', 'total_tokens_used',
               existing_type=sa.BIGINT(),
               server_default=sa.text("'0'::bigint"),
               existing_nullable=False)
    op.alter_column('conversations', 'total_messages',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('ix_citations_document_id'), 'citations', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_embedding_hnsw'), 'chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw', postgresql_where='(embedding IS NOT NULL)')
    op.create_index(op.f('ix_chunks_content_tsv'), 'chunks', ['content_tsv'], unique=False, postgresql_using='gin', postgresql_where='(content_tsv IS NOT NULL)')
    op.alter_column('chunks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('chunks', 'embedding_status',
               existing_type=postgresql.ENUM('pending', 'embedded', 'failed', name='embedding_status'),
               server_default=sa.text("'pending'::embedding_status"),
               existing_nullable=False)
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_memberships_tenant_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_roles_tenant_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
